"use client";

export const notifications = [
  {
    friendName: "Mark Webber",
    friendPic: "url",
    notificationType: "reacted to your recent post",
    notificationValue: "My first tournament today!",
    read: false,
    time: "1m",
    id: 1,
  },
  {
    friendName: "Angela Gray",
    friendPic: "url",
    notificationType: "followed you",
    notificationValue: "",
    read: false,
    time: "5m",
    id: 2,
  },
  {
    friendName: "Jacob Thompson",
    friendPic: "url",
    notificationType: "has joined your group",
    notificationValue: "Chess Club",
    read: false,
    time: "1 day",
    id: 3,
  },
  {
    friendName: "Rizky Hassanuddin",
    friendPic: "url",
    notificationType: "sent you a private message",
    notificationValue:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    read: false,
    time: "5 days",
    id: 4,
  },
  {
    friendName: "Kimberly Smith",
    friendPic: "url",
    notificationType: "commented on your picture",
    notificationValue: "pic URL",
    read: false,
    time: "1 week",
    id: 5,
  },
  {
    friendName: "Nathan Peterson",
    friendPic: "url",
    notificationType: "reacted to your recent post",
    notificationValue: "5 end-game strategies to increase your win rate",
    read: false,
    time: "2 weeks",
    id: 6,
  },
  {
    friendName: "Anna Kim",
    friendPic: "url",
    notificationType: "left the group group",
    notificationValue: "Chess Club",
    read: false,
    time: "2 weeks",
    id: 7,
  },
];
