import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Providers } from "./GlobalRedux/provider";

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Notifications Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
